// src/page/workbench/component/BarChart/index.tsx
import { FC } from 'react'
import { useEcharts } from '@/hooks/useEcharts'
import type { EChartsOption } from 'echarts'
import * as echarts from 'echarts'

interface PropsType {
  className?: string
  width?: string
  height?: string
}
const BarChart: FC<PropsType> = (props) => {
  const { className, width, height } = props
  const options: EChartsOption = {
    tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'line'
      },
      formatter: (params) =>
        `${params[0].name}<br/>${params[0].marker}${
          params[0].seriesName
        }：${params[0].value.toLocaleString()} 亿元`
    },
    grid: {
      bottom: 0,
      top: 0,
      right: 60,
      left: 50
    },
    color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [
      {
        offset: 0,
        color: '#3ED473'
      },
      {
        offset: 1,
        color: '#399EFB'
      }
    ]),
    xAxis: {
      type: 'value',
      show: false
    },
    yAxis: [
      {
        type: 'category',
        inverse: true,
        axisLabel: {
          show: true
        },
        splitLine: {
          show: false
        },
        axisTick: 'none',
        axisLine: {
          show: false
        },
        data: ['南山区', '福田区', '罗湖区', '宝安区', '龙华区', '龙岗区']
      }
    ],
    series: [
      {
        name: '累计消费',
        type: 'bar',
        itemStyle: {
          borderRadius: 4
        },
        barWidth: 25,
        data: [650, 390, 374, 341, 302, 320],
        label: {
          show: true,
          position: 'right',
          color: '#399EFB',
          fontSize: 14,
          formatter: '{c}亿元'
        }
      }
    ]
  }
  const { chartRef, setOption } = useEcharts(options)

  return (
    <div
      ref={chartRef}
      className={className}
      style={{
        width,
        height
      }}
    ></div>
  )
}

BarChart.defaultProps = {
  className: '',
  height: '300px',
  width: '100%'
}
export default BarChart

// src/views/dashboard/component/BarChart.vue
<template>
  <div
    ref="chartRef"
    :class="className"
    :style="{ height: height, width: width }"
  />
</template>
<script setup lang="ts">
import type { EChartsOption } from 'echarts'
import { ref, watch } from 'vue'
import { useEcharts } from '@/hooks/useEcharts'
const props = defineProps({
  className: {
    type: String,
    default: 'chart',
  },
  width: {
    type: String,
    default: '100%',
  },
  height: {
    type: String,
    default: '300px',
  },
})
const data_1 = ref<number[]>([79, 52, 200, 334, 390, 330, 220])
const data_2 = ref<number[]>([79, 52, 200, 334, 390, 330, 220])
const data_3 = ref<number[]>([79, 52, 200, 334, 390, 330, 220])
const animationDuration = 300
const option = ref<EChartsOption>({
  tooltip: {
    trigger: 'item',
  },
  grid: {
    top: 10,
    left: '2%',
    right: '2%',
    bottom: '3%',
    containLabel: true,
  },
  xAxis: [
    {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      axisTick: {
        alignWithLabel: true,
      },
    },
  ],
  yAxis: [
    {
      type: 'value',
      axisTick: {
        show: false,
      },
    },
  ],
  series: [
    {
      name: 'pageA',
      type: 'bar',
      stack: 'vistors',
      barWidth: '60%',
      data: data_1.value,
      animationDuration,
    },
    {
      name: 'pageB',
      type: 'bar',
      stack: 'vistors',
      barWidth: '60%',
      data: data_2.value,
      animationDuration,
    },
    {
      name: 'pageC',
      type: 'bar',
      stack: 'vistors',
      barWidth: '60%',
      data: data_3.value,
      animationDuration,
    },
  ],
})
const chartRef = ref<HTMLElement>()
const { setOption } = useEcharts(option.value as EChartsOption, chartRef)
watch(
  () => option.value,
  (newValue) => {
    setOption(newValue as EChartsOption)
  },
  {
    deep: true,
  }
)
</script>

<style scoped></style>
