// src/page/dashboard/component/LineChart/index.tsx
import { FC } from 'react'
import { useEcharts } from '@/hooks/useEcharts'
import type { EChartsOption } from 'echarts'

interface PropsType {
  className?: string
  width?: string
  height?: string
}

const LineChart: FC<PropsType> = (props) => {
  const { className, width, height } = props
  const options: EChartsOption = {
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
      splitLine: {
        show: true
      },
      axisTick: {
        show: false
      }
    },
    yAxis: {
      boundaryGap: false,
      type: 'value'
    },
    tooltip: {
      trigger: 'axis'
    },
    grid: {
      bottom: 20,
      top: 10,
      right: 15,
      left: 50
    },
    series: [
      {
        data: [1279, 2522, 3225, 4552, 5255, 1200, 4500, 6252, 1456, 1252, 1567, 8956],
        name: '签单',
        type: 'line',
        symbolSize: 1,
        symbol: 'circle',
        smooth: true,
        showSymbol: false,
        color: '#39C3D5',
        lineStyle: {
          width: 3,
          shadowColor: 'rgba(252, 177, 17, 0)',
          shadowBlur: 10,
          shadowOffsetY: 20
        },
        areaStyle: {
          color: '#39C3D5'
        }
      },
      {
        data: [2905, 4565, 1548, 5555, 555, 4514, 8874, 4512, 4854, 5888, 9666, 1244],
        name: '回款',
        type: 'line',
        yAxisIndex: 0,
        symbolSize: 1,
        color: '#46A6FF',
        symbol: 'circle',
        showSymbol: false,
        smooth: true,
        lineStyle: {
          width: 3,
          shadowColor: 'rgba(252, 177, 17, 0)',
          shadowBlur: 10,
          shadowOffsetY: 20
        },
        areaStyle: {
          color: '#46A6FF'
        }
      }
    ]
  }
  const { chartRef, setOption } = useEcharts(options)

  return (
    <div
      ref={chartRef}
      className={className}
      style={{
        width,
        height
      }}
    ></div>
  )
}

LineChart.defaultProps = {
  className: '',
  height: '200px',
  width: '100%'
}

export default LineChart

// src/views/dashboard/component/LineChart.vue
<template>
  <div
    ref="chartRef"
    :class="className"
    :style="{ height: height, width: width }"
  />
</template>

<script setup lang="ts">
import type { EChartsOption } from 'echarts'
import { ref, watch } from 'vue'
import { useEcharts } from '@/hooks/useEcharts'
const props = defineProps({
  className: {
    type: String,
    default: 'chart',
  },
  width: {
    type: String,
    default: '100%',
  },
  height: {
    type: String,
    default: '350px',
  },
  chartData: {
    type: Object,
    required: true,
  },
})
const chartRef = ref<HTMLElement>()
function setData(data: any) {
  return {
    xAxis: {
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      boundaryGap: false,
      axisTick: {
        show: false,
      },
    },
    grid: {
      left: 10,
      right: 10,
      bottom: 20,
      top: 30,
      containLabel: true,
    },
    tooltip: {
      trigger: 'item',
    },
    yAxis: {
      axisTick: {
        show: false,
      },
    },
    legend: {
      data: ['expected', 'actual'],
    },
    series: [
      {
        name: 'expected',
        itemStyle: {
          borderWidth: 2,
          borderColor: '#FFF',
        },
        lineStyle: {
          shadowBlur: 12,
          shadowColor: 'rgba(43, 184, 208, 1)',
          shadowOffsetX: 1,
          shadowOffsetY: 1,
        },
        smooth: true,
        symbol: 'none',
        type: 'line',
        data: data.expectedData,
        animationDuration: 2800,
        animationEasing: 'cubicInOut',
      },
      {
        name: 'actual',
        smooth: true,
        type: 'line',
        symbol: 'none',
        itemStyle: {
          borderWidth: 2,
          borderColor: '#FFF',
        },
        lineStyle: {
          shadowBlur: 12,
          shadowColor: 'rgba(92, 139, 218, 1)',
          shadowOffsetX: 1,
          shadowOffsetY: 1,
        },
        data: data.actualData,
        animationDuration: 2800,
        animationEasing: 'quadraticOut',
      },
    ],
  }
}
const { setOption } = useEcharts(
  setData(props.chartData) as EChartsOption,
  chartRef
)
watch(
  () => props.chartData,
  (newValue) => {
    setOption(setData(newValue) as EChartsOption)
  }
)
</script>

<style scoped></style>
